---

- name: create user group
  become: yes
  group: name="{{ bots_group }}"
         gid=6001
  ignore_errors: true

- name: create user
  become: yes
  user: name="{{ bots_user }}"
        password="{{ bots_password }}"
        state=present
        shell=/bin/bash
        uid=6001
        groups="{{ bots_group }},sudo"
  tags: users
  ignore_errors: true
