---

- name: check out git repository
  git: repo={{ tinyskylines_project_repo_url }}
       dest={{ tinyskylines_project_root }}
       accept_hostkey=yes
       force=yes
  when: is_vagrant != True

- name: symlink executable
  become: yes
  file:
      src: "{{ tinyskylines_project_root }}/bin/{{ tinyskylines_project_executable_name }}"
      dest: "{{ bin_root }}/{{ tinyskylines_project_executable_name }}"
      owner: "{{ bots_user }}"
      group: "{{ bots_user }}"
      state: link

- name: create data directory
  become: yes
  file:
      path: "{{ tinyskylines_project_data_dir }}"
      owner: "{{ bots_user }}"
      group: "{{ bots_user }}"
      mode: 0755
      state: directory
      recurse: yes
  when: is_vagrant != True

# cron
- include_vars: cron.yml

- name: copy the cron file
  become: yes
  copy: content="{{ tinyskylines_cron }}"
        dest="/etc/cron.d/{{ tinyskylines_project_name }}"
        mode=0644
        owner="root"
        group="root"
  when: is_vagrant != True

# configure API keys
- block:
  - name: include development variables
    include_vars: development.yml
  when: is_vagrant == True

- block:
  - name: include production variables
    include_vars: production.yml
  when: is_vagrant != True

- include: twitter.yml
