---

- include_vars: keys.yml

- name: copy the SSH public key file
  become: yes
  copy: content="{{ gitlab_ssh_public_key }}"
        dest="~{{ gitlab_key_user }}/.ssh/gitlab_rsa.pub"
        mode=0600
        owner="{{ gitlab_key_user }}"
        group="{{ gitlab_key_user }}"

- name: copy the SSH private key file
  become: yes
  copy: content="{{ gitlab_ssh_private_key }}"
        dest="~{{ gitlab_key_user }}/.ssh/gitlab_rsa"
        mode=0600
        owner="{{ gitlab_key_user }}"
        group="{{ gitlab_key_user }}"

- name: set up ~/.ssh/config
  become: yes
  lineinfile: dest="~{{ gitlab_key_user }}/.ssh/config"
              line="{{ gitlab_key_ssh_config }}"
              create=yes
              owner="{{ gitlab_key_user }}"
              group="{{ gitlab_key_user }}"
